window.SHELDON_GLOSSARY = {
  "weekend": "выходные",
  "hygiene": "гигиена",
  "cool": "крутой",
  "taxes": "налоги",
  "secret": "секрет",
  "fish sauce": "рыбный соус",
  "allowance": "карманные деньги",
  "savings": "сбережения",
  "bank": "банк",
  "account": "счёт",
  "budget": "бюджет",
  "expenses": "расходы",
  "income": "доход",
  "mortgage": "ипотека",
  "debt": "долг",
  "loan": "заём",
  "interest": "процент",
  "church": "церковь",
  "pastor": "пастор",
  "neighbor": "сосед",
  "homework": "домашнее задание",
  "college": "колледж",
  "genius": "гений",
  "awkward": "неловкий",
  "embarrassed": "смущённый",
  "upset": "расстроенный",
  "worried": "обеспокоенный",
  "honest": "честный",
  "trust": "доверие",
  "family": "семья",
  "brother": "брат",
  "sister": "сестра",
  "parents": "родители",
  "dad": "папа",
  "mom": "мама",
  "grandma": "бабушка",
  "grandpa": "дедушка",
};
