import type { TopicContent } from '../../components/TopicContent'

export const examMacroKeyQuestions: TopicContent = [
  { type: 'p', en: 'Exam Q&A: consumption, income elasticity, CB bond sales, post-recession, IS-LM numerics.', ru: 'Экзамен: потребление, YED, ЦБ, рецессия, IS-LM числа.' },
  { type: 'h2', en: 'What is consumption (C)?', ru: 'Что такое потребление?' },
  { type: 'p', en: 'Macro: household spending on goods and services. Y = C + I + G + NX. Not the same as Frank micro consumer choice.', ru: 'Макро: расходы домохозяйств. Y = C + I + G + NX.' },
  { type: 'hr' },
  { type: 'h2', en: 'Consumption function', ru: 'Функция потребления' },
  { type: 'formula', lines: ['C = c₀ + c₁Y', 'MPC = c₁', 'MPS = 1 − MPC', 'Slope of C(Y) = MPC'] },
  { type: 'hr' },
  { type: 'h2', en: 'C when Y = 0', ru: 'C при Y = 0' },
  { type: 'p', en: 'C = c₀ > 0 — dissaving from savings/credit/transfers. Break-even: Y* = c₀/(1−c₁).', ru: 'C = c₀ > 0 — dissaving. Y* = c₀/(1−c₁).' },
  { type: 'hr' },
  { type: 'h2', en: 'Income elasticity (YED)', ru: 'Доходная эластичность' },
  { type: 'formula', lines: ['YED = (%ΔQ) / (%ΔY)', 'YED > 0 normal · YED < 0 inferior · YED > 1 luxury'] },
  { type: 'hr' },
  { type: 'h2', en: 'CB sells bonds', ru: 'ЦБ продаёт облигации' },
  { type: 'p', en: 'M↓ → LM left → i↑ → I↓, C↓ → Y↓. Buy bonds → opposite.', ru: 'M↓ → i↑ → Y↓. Покупка → наоборот.' },
  { type: 'hr' },
  { type: 'h2', en: 'After recession', ru: 'После рецессии' },
  { type: 'p', en: 'Y↑, u↓, C↑, I↑. Expansionary policy: G↑, T↓, M↑, i↓.', ru: 'Y↑, u↓, C↑, I↑. Стимулирующая политика.' },
  { type: 'hr' },
  { type: 'h2', en: 'IS-LM numerics', ru: 'IS-LM числа' },
  { type: 'formula', lines: ['IS: Y = C + I + G', 'LM: M = L(Y, i)', 'Example: i* = 4, Y* = 880'] },
]
