import type { TopicContent } from '../../components/TopicContent'

export const productionFunction: TopicContent = [
  { type: 'p', en: 'Source: Frank, Microeconomics and Behavior, 7th ed., Ch. 8 (Production). Kitchen example, diminishing returns, MP–AP rules, MC = w/MP.', ru: 'Источник: Frank, Ch. 8. Пример кухни, убывающая отдача, правила MP/AP, MC = w/MP.' },
  { type: 'h2', en: 'What is a Production Function?', ru: 'Что такое производственная функция?' },
  { type: 'p', en: 'Maximum output Q from inputs L and K with given technology. Short run: Q = f(L, K̄) with K fixed.', ru: 'Максимальный выпуск Q при заданных L, K и технологии. Краткосрочно: Q = f(L, K̄), K фиксирован.' },
  { type: 'formula', lines: ['Q = F(L, K, …)', 'SR: TP = Q = f(L, K̄)'] },
  { type: 'p', en: 'Do not confuse: diminishing returns (SR, +L with fixed K) vs returns to scale (LR, scale both L and K).', ru: 'Не путать: убывающая отдача (SR) и масштаб возврата (LR).' },
  { type: 'hr' },
  { type: 'h2', en: 'TP, MP, AP', ru: 'TP, MP, AP' },
  { type: 'table', headers: ['Term', 'Formula', 'Meaning'], rows: [
    ['Total Product (TP)', 'Q = f(L, K̄)', 'Total output'],
    ['Marginal Product (MP)', 'MP = ΔQ / ΔL', 'Extra output from one more worker'],
    ['Average Product (AP)', 'AP = Q / L', 'Output per worker'],
  ]},
  { type: 'p', en: 'Frank: 5 workers → 50 parts; 6 workers → 56 parts. MP of 6th = 6. AP at L=6: 56/6 ≈ 9.3.', ru: 'Frank: 5 рабочих → 50 деталей; 6 → 56. MP 6-го = 6. AP при L=6 ≈ 9,3.' },
  { type: 'hr' },
  { type: 'h2', en: 'Frank kitchen example (fixed K)', ru: 'Пример Frank — кухня (K фиксирован)' },
  { type: 'table', headers: ['L', 'Q', 'MP', 'AP'], rows: [
    ['1', '10', '10', '10.0'],
    ['2', '25', '15', '12.5'],
    ['3', '35', '10', '11.7'],
    ['4', '40', '5', '10.0'],
    ['5', '41', '1', '8.2'],
    ['6', '38', '−3', '6.3'],
  ]},
  { type: 'p', en: 'Specialization at first (MP rises), then crowding (MP falls), then MP < 0 at L=6.', ru: 'Сначала специализация, потом теснота, при L=6 MP < 0 — TP падает.' },
  { type: 'hr' },
  { type: 'h2', en: 'Law of diminishing returns', ru: 'Закон убывающей отдачи' },
  { type: 'p', en: 'Adding variable input L to fixed K → MP eventually falls. TP max when MP = 0.', ru: 'При фиксированном K MP в итоге падает. TP максимален, когда MP = 0.' },
  { type: 'hr' },
  { type: 'h2', en: 'MP and AP rules', ru: 'Правила MP и AP' },
  { type: 'p', en: 'MP > AP → AP rises. MP < AP → AP falls. MP crosses AP at max AP. Class-average analogy (Frank).', ru: 'MP > AP → AP растёт. MP < AP → AP падает. MP пересекает AP в максимуме AP.' },
  { type: 'hr' },
  { type: 'h2', en: 'Three stages of production', ru: 'Три стадии производства' },
  { type: 'table', headers: ['Stage', 'Condition', 'Description'], rows: [
    ['I', 'MP > AP', 'Specialization, underused K'],
    ['II', 'MP < AP, MP > 0', 'Rational zone — diminishing returns'],
    ['III', 'MP < 0', 'Extra L reduces Q'],
  ]},
  { type: 'hr' },
  { type: 'h2', en: 'Mirror: MP and MC', ru: 'Зеркало: MP и MC' },
  { type: 'formula', lines: ['MC = w / MP_L', 'AVC = w / AP_L'] },
  { type: 'p', en: 'Falling MP (diminishing returns) → rising MC. U-shaped AVC/ATC in Ch. 9.', ru: 'Падение MP → рост MC. U-образные AVC/ATC в Ch. 9.' },
  { type: 'hr' },
  { type: 'h2', en: 'Long run (Ch. 9)', ru: 'Долгосрочный период (Ch. 9)' },
  { type: 'p', en: 'Q = f(L, K), isoquants, MRTS = w/r. Bakery: 100 pies with 10 bakers + 2 ovens or 3 bakers + 5 ovens.', ru: 'Q = f(L, K), изокванты, MRTS = w/r. Пекарня: 100 пирогов разными комбинациями L и K.' },
]
